# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myluck

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://fabioreg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5a4d09442d4a423ab397b030c9e489e4 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_79aadf08022243f392966ccfd4c51e06 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: fabioreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5a4d09442d4a423ab397b030c9e489e4 }}/myluck:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myluck'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c2dbf25e2b5648e98d263de235a9801d }}
        images: 'fabioreg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5a4d09442d4a423ab397b030c9e489e4 }}/myluck:${{ github.sha }}'